// רשימת אמנים חרדיים/חסידיים – מקור: המכלול + zingmusic + נוספים
// type: "singer" = זמר, "band" = להקה, "choir" = מקהלה
// searchName = שם לחיפוש ב-YouTube (עברית + אנגלית)

const ARTISTS = [
  // === מהמכלול – קטגוריה:זמרים חסידיים ===
  { name: "אברהם אבוטבול", searchName: "avraham abutbul", type: "singer" },
  { name: "אודי אולמן", searchName: "udi ulman", type: "singer" },
  { name: "אייבי רוטנברג", searchName: "abie rotenberg", type: "singer" },
  { name: "פיני איינהורן", searchName: "pini einhorn", type: "singer" },
  { name: "מוטי אילוביץ", searchName: "moti ilowitz", type: "singer" },
  { name: "אבי אילסון", searchName: "avi ilson", type: "singer" },
  { name: "רבי אלתר", searchName: "rebbe alter", type: "singer" },
  { name: "רפי ביטון", searchName: "rafi biton", type: "singer" },
  { name: "אבי בן ישראל", searchName: "avi ben israel", type: "singer" },
  { name: "קן ברג'ס", searchName: "ken burgess", type: "singer" },
  { name: "ברוך שלום בלסופסקי", searchName: "baruch shalom blesofsky", type: "singer" },
  { name: "ארי גולדוואג", searchName: "ari goldwag", type: "singer" },
  { name: "יהודה גלאנץ", searchName: "yehuda glanz", type: "singer" },
  { name: "יהודה גרובייס", searchName: "yehuda grubays", type: "singer" },
  { name: "שלומי גרטנר", searchName: "shlomi gertner", type: "singer" },
  { name: "יוסי גרין", searchName: "yossi green", type: "singer" },
  { name: "אלי גרסטנר", searchName: "eli gerstner", type: "singer" },
  { name: "שלומי דאקס", searchName: "shlomi daks", type: "singer" },
  { name: "איציק דדיה", searchName: "itzik dadya", type: "singer" },
  { name: "ירמיה דמן", searchName: "yirmiya damen", type: "singer" },
  { name: "יעקב יהודה דסקל", searchName: "shloimy daskal", type: "singer" },
  { name: "אייזיק האניג", searchName: "isaac honig", type: "singer" },
  { name: "ארי היל", searchName: "ari hill", type: "singer" },
  { name: "עופר הלוי", searchName: "ofer halevi", type: "singer" },
  { name: "יצחק מאיר הלפגוט", searchName: "yitzchak meir helfgot", type: "singer" },
  { name: "חיים אליעזר הרשטיק", searchName: "chaim elazar hershtik", type: "singer" },
  { name: "נפתלי הרשטיק", searchName: "naftali hershtik", type: "singer" },
  { name: "מוטי וייס", searchName: "moti weiss", type: "singer" },
  { name: "צבי וייס", searchName: "tzvi weiss", type: "singer" },
  { name: "דוד וינבך", searchName: "dovid weinbach", type: "singer" },
  { name: "טל ועקנין", searchName: "tal vaknin", type: "singer" },
  { name: "יידל ורדיגר", searchName: "yeedel werdyger", type: "singer" },
  { name: "הרב ברוך חייט", searchName: "baruch chait", type: "singer" },
  { name: "גבריאל חסון", searchName: "gavriel hasson", type: "singer" },
  { name: "בריו חקשור", searchName: "brio chakshur", type: "singer" },
  { name: "הראל טל", searchName: "harel tal", type: "singer" },
  { name: "מידד טסה", searchName: "medad tasa", type: "singer" },
  { name: "רועי ידיד", searchName: "roi yedid", type: "singer" },
  { name: "יהודה דים", searchName: "yehuda dim", type: "singer" },
  { name: "יוני זי", searchName: "yoni z", type: "singer" },
  { name: "יוסף משה כהנא", searchName: "yosef moshe kahana", type: "singer" },
  { name: "יאיר כלב", searchName: "yair kalev", type: "singer" },
  { name: "איתן כץ", searchName: "eitan katz", type: "singer" },
  { name: "ברוך לוין", searchName: "baruch levine", type: "singer" },
  { name: "יהושע לימוני", searchName: "yehoshua limoni", type: "singer" },
  { name: "אלי ליפסקר", searchName: "eli lipsker", type: "singer" },
  { name: "ביני לנדאו", searchName: "bini landau", type: "singer" },
  { name: "ישי לפידות", searchName: "yishai lapidot", type: "singer" },
  { name: "יצחק מאיר", searchName: "yitzchak meir", type: "singer" },
  { name: "אוהד מושקוביץ", searchName: "ohad moskowitz", type: "singer" },
  { name: "אלי מרקוס", searchName: "eli marcus", type: "singer" },
  { name: "נמואל הרוש", searchName: "nemuel harush", type: "singer" },
  { name: "ארמונד סוסנה", searchName: "armond susana", type: "singer" },
  { name: "יובל סטופל", searchName: "yuval stupel", type: "singer" },
  { name: "שוקי סלומון", searchName: "shuki solomon", type: "singer" },
  { name: "יהודה סעדו", searchName: "yehuda saado", type: "singer" },
  { name: "יום טוב עהרליך", searchName: "yom tov ehrlich", type: "singer" },
  { name: "גלעד פוטולסקי", searchName: "gilad potolsky", type: "singer" },
  { name: "אבי פיאמנטה", searchName: "avi piamenta", type: "singer" },
  { name: "ירמיהו פיחה", searchName: "yirmiyahu picha", type: "singer" },
  { name: "מנחם פיליפ", searchName: "menachem philip", type: "singer" },
  { name: "בני פרידמן", searchName: "benny friedman", type: "singer" },
  { name: "ישראל פרנס", searchName: "israel parnas", type: "singer" },
  { name: "עוזיה צדוק", searchName: "uziya tzadok", type: "singer" },
  { name: "מיילך קאהן", searchName: "meilech kohn", type: "singer" },
  { name: "דודי קאליש", searchName: "dudi kalish", type: "singer" },
  { name: "הרב מנחם קליין", searchName: "menachem klein", type: "singer" },
  { name: "שיבי קלר", searchName: "shivi keller", type: "singer" },
  { name: "יוסף קרדונר", searchName: "yosef karduner", type: "singer" },
  { name: "שלמה קרליבך", searchName: "shlomo carlebach", type: "singer" },
  { name: "אהרן רזאל", searchName: "aharon razel", type: "singer" },
  { name: "יונתן רזאל", searchName: "yonatan razel", type: "singer" },
  { name: "יוסף חיים שוואקי", searchName: "yosef chaim shwekey", type: "singer" },
  { name: "יעקב שוואקי", searchName: "yaakov shwekey", type: "singer" },
  { name: "יונתן שוורץ", searchName: "yonatan schwartz", type: "singer" },
  { name: "דב שורין", searchName: "dov shurin", type: "singer" },
  { name: "שימי אנגל", searchName: "shimi engel", type: "singer" },
  { name: "יונתן שינפלד", searchName: "yonatan shainfeld", type: "singer" },
  { name: "יוני שלמה", searchName: "yoni shlomo", type: "singer" },
  { name: "ליפא שמלצר", searchName: "lipa schmeltzer", type: "singer" },
  { name: "מיכאל שניצלר", searchName: "michoel schnitzler", type: "singer" },
  { name: "אלעד שער", searchName: "elad shaar", type: "singer" },
  { name: "מרדכי שפירא", searchName: "mordechai shapiro", type: "singer" },
  { name: "סיני תור", searchName: "sinai tor", type: "singer" },

  // === זמרים אמריקאים / בינלאומיים מובילים ===
  { name: "ישי ריבו", searchName: "ishay ribo", type: "singer" },
  { name: "מוטי שטיינמץ", searchName: "motty steinmetz", type: "singer" },
  { name: "שמואלי אונגר", searchName: "shmueli ungar", type: "singer" },
  { name: "בערי וובר", searchName: "beri weber", type: "singer" },
  { name: "שמחה ליינר", searchName: "simcha leiner", type: "singer" },
  { name: "אברהם פריד", searchName: "avraham fried", type: "singer" },
  { name: "מרדכי בן דוד", searchName: "mordechai ben david MBD", type: "singer" },
  { name: "זנוויל וויינברגר", searchName: "zanvil weinberger", type: "singer" },
  { name: "שלום למר", searchName: "shulem lemmer", type: "singer" },
  { name: "לוי פלקוביץ", searchName: "levy falkowitz", type: "singer" },
  { name: "משה שטרך", searchName: "moshe storch", type: "singer" },
  { name: "שלמה ידגר", searchName: "shlomo yidgar", type: "singer" },
  { name: "נחמן פילמר", searchName: "nachman filmer", type: "singer" },

  // === ערוצים / פרויקטים מוזיקליים ===
  { name: "TYH Nation", searchName: "TYH Nation", type: "band" },
  { name: "Shiezoli", searchName: "shiezoli", type: "singer" },
  { name: "Jewish Music AI", searchName: "jewish music AI", type: "band" },
  { name: "יענקלה AI", searchName: "yankele AI jewish", type: "band" },
  { name: "שיר בוט", searchName: "shir bot", type: "band" },
  { name: "8th Day", searchName: "8th day jewish", type: "band" },

  // === מקהלות ===
  { name: "פרחי לונדון", searchName: "pirchei london", type: "choir" },
  { name: "פרחי מיאמי", searchName: "miami boys choir", type: "choir" },
  { name: "זושא", searchName: "zusha band", type: "band" },
  { name: "צליל וזמר", searchName: "tzlil vzemer", type: "choir" },
  { name: "צמד רעים", searchName: "tzemad re'im", type: "band" },
];

module.exports = ARTISTS;
